"""Core data model (Game Master + actors design).

The truth of a case (profession + fault) is SAMPLED IN CODE from buzzwords.pools —
never generated — so the smokescreen holds by construction. The director model writes
only the oblique ``facts``. The transcript is built one ``Line`` at a time; each line
is already in-character jargon. At the end the hidden truth is revealed and the
player's plain-English guess is scored.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class CaseFile:
    """Hidden ground truth. profession+fault sampled from pools; facts model-written."""

    profession: str             # revealed only at the end
    fault_plain: str            # the charge in plain English (verb phrase) -> reveal + scoring
    facts: list[str] = field(default_factory=list)   # oblique clues, fed to actors by index
    turn_budget: int = 10       # contracts.TURN_BUDGET (fixed; difficulty was removed)


@dataclass
class GMDecision:
    """One structured beat from the Game Master (GBNF-constrained at runtime)."""

    next_speaker: str           # judge | prosecutor | defense
    beat_type: str = "exchange"
    fact_index: Optional[int] = None   # which case-file fact to surface this beat (or None)
    line: str = ""              # the spoken line in PLAIN English (SHAPE 3.0)
    intensity: int = 3          # 1..5
    wrap_up: bool = False       # True -> the debate should head to closure


@dataclass
class Line:
    actor: str                  # role key: judge | prosecutor | defense (matches BUBBLES)
    text: str                   # the in-character JARGON line shown to the player
    plain_text: str = ""        # the director's plain-English original (reveal screen)
    beat_type: str = ""         # the GMDecision.beat_type that produced it
    fact_index: Optional[int] = None   # the fact this line carries


@dataclass
class Case:
    case_file: CaseFile                      # hidden truth
    jargon_style: str = "corporate"          # selects background + actor LoRA style
    lines: list[Line] = field(default_factory=list)   # the transcript, built up live
    facts_released: set[int] = field(default_factory=set)  # clue-economy bookkeeping


@dataclass
class GameSession:
    """Per-user state held in gr.State (one instance per browser session).

    Beats are generated by a background worker (pipeline.start_generation) while the
    player reads — `turn`/`wrapped`/`gen_done` are written by the worker, the playback
    fields by the UI handlers (single writer each; reads are snapshot-tolerant)."""

    case: Optional[Case] = None
    turn: int = 0                    # beats GENERATED so far
    wrapped: bool = False            # GM signalled closure (or budget spent)
    gen_done: bool = False           # worker finished (success, early-close, or error)
    gen_error: str = ""              # non-empty -> worker aborted with this message
    playback_idx: int = 0            # which generated line the player is viewing
    guess: str = ""
    score: Optional[int] = None
    rationale: str = ""

    @property
    def budget(self) -> int:
        return self.case.case_file.turn_budget if self.case else 0

    @property
    def generation_finished(self) -> bool:
        """True once generation has reached closure (wrap_up honored or out of budget)."""
        if not self.case:
            return False
        return self.wrapped or self.turn >= self.budget

    @property
    def playback_done(self) -> bool:
        """True once the player is on the last line AND no more lines are coming."""
        if not self.case or not self.case.lines:
            return False
        return self.gen_done and self.playback_idx >= len(self.case.lines) - 1

    def current_line(self) -> Optional[Line]:
        if not self.case or not self.case.lines:
            return None
        return self.case.lines[min(self.playback_idx, len(self.case.lines) - 1)]

    def next_line_ready(self) -> bool:
        return bool(self.case) and self.playback_idx + 1 < len(self.case.lines)
