"""Curated jargon banks, one list per style.

Used to ANCHOR the teacher: each generation prompt gets a
random seeded subset of its style's bank woven in, so transcripts pull from the full
vocabulary instead of the model recycling the same five phrases. Keys must match
config.JARGONS / teacher_datagen.STYLES.

Edit freely -- add terms to enrich a style, or tune for difficulty (obscure vs common).
"""

JARGON = {
    "aviation": [
        "sterile cockpit", "V1 cut", "go-around", "glide slope", "NOTAM", "squawk code",
        "squawk 7700", "transponder", "TCAS alert", "CFIT", "VFR", "IMC", "exceeding Vne",
        "never-exceed speed", "type rating", "wind shear", "flameout", "holding pattern",
        "Minimum Equipment List", "positive rate of climb", "pre-flight checklist", "black box",
        "flight data recorder", "stall", "deep stall", "crosswind", "tailwind", "headwind",
        "pushback", "angle of attack", "decision height", "missed approach", "ATC clearance",
        "trim and yaw", "pitch and bank", "runway incursion", "dead reckoning", "ground stop",
        "mayday", "pan-pan", "loss of separation", "stabilized approach", "flaps and slats",
        "landing gear", "METAR", "ILS approach", "localizer", "autopilot disengage",
        "autothrottle", "coffin corner", "service ceiling", "bingo fuel", "fuel dump", "ETOPS",
        "deadstick landing", "touch-and-go", "hold short", "rejected takeoff", "rotate and climb",
        "descent profile", "flight level three-five-zero", "cabin pressurization", "hypoxia",
        "spatial disorientation", "controlled airspace", "restricted airspace", "wake turbulence",
        "crosscheck", "flight envelope", "attitude indicator", "artificial horizon",
        "vertical speed", "terrain pull-up", "EGPWS warning", "single-engine-out",
        "feathered prop", "jet wash", "contrail", "taxiway", "the apron", "back on the throttle",
    ],
    "corporate": [
        "synergy", "leverage", "circle back", "low-hanging fruit", "move the needle",
        "boil the ocean", "bandwidth", "deep dive", "touch base", "drill down", "value-add",
        "core competency", "paradigm shift", "scalable", "actionable", "deliverable",
        "stakeholder alignment", "KPI", "north-star metric", "ROI", "pivot", "growth hacking",
        "take it offline", "ducks in a row", "right-size", "streamline", "holistic", "ideate",
        "operationalize", "double-click on that", "table stakes", "blue-sky thinking",
        "run it up the flagpole", "mission-critical", "boots on the ground",
        "move fast and break things", "eat our own dog food", "drink the Kool-Aid",
        "open the kimono", "peel the onion", "herding cats", "swim lane", "helicopter view",
        "30,000-foot view", "in the weeds", "on my radar", "ping me", "loop you in", "sync up",
        "align on", "socialize the idea", "unpack that", "the ask", "key learnings", "optionality",
        "win-win", "quick win", "big rock", "moving parts", "cadence", "all-hands", "fire drill",
        "churn", "runway", "burn rate", "bleeding edge", "best-in-class", "frictionless",
        "turnkey", "pain point", "value proposition", "secret sauce", "thought leadership",
        "going forward", "net-net", "at the end of the day", "lift and shift", "circle of trust",
        "raise the bar", "boil it down", "north of that number",
    ],
    "ai": [
        "neural network", "gradient descent", "overfitting", "underfitting", "hallucination",
        "fine-tuning", "token budget", "embedding", "attention head", "transformer",
        "backpropagation", "loss function", "hyperparameter", "training data", "inference",
        "latent space", "prompt injection", "RLHF", "context window", "quantization",
        "model weights", "epoch", "batch size", "alignment", "emergent behavior", "zero-shot",
        "few-shot", "ground truth", "model collapse", "vector embedding", "benchmark",
        "distillation", "checkpoint", "learning rate", "convergence", "dataset bias",
        "reward hacking", "activation function", "softmax", "logits", "temperature sampling",
        "top-p sampling", "beam search", "tokenizer", "vocabulary size", "parameter count",
        "scaling laws", "compute budget", "GPU cluster", "mixture of experts", "self-attention",
        "positional encoding", "layer normalization", "dropout", "regularization",
        "validation loss", "gradient clipping", "vanishing gradients", "exploding gradients",
        "transfer learning", "pretraining", "downstream task", "catastrophic forgetting",
        "data augmentation", "feature extraction", "dimensionality reduction", "clustering",
        "classification", "confusion matrix", "precision and recall", "F1 score",
        "early stopping", "the ensemble", "black-box model", "explainability", "model drift",
        "out-of-distribution", "frozen layers", "the embedding space",
    ],
    "politics": [
        "bipartisan", "filibuster", "filibuster-proof", "gerrymander", "swing state",
        "talking points", "spin", "optics", "the base", "flip-flop", "lame duck", "pork-barrel",
        "lobby", "caucus", "mandate", "grassroots", "town hall", "platform", "incumbent",
        "landslide", "war chest", "attack ad", "dog whistle", "reach across the aisle",
        "kick the can", "October surprise", "exit poll", "stump speech", "on message",
        "walk it back", "photo op", "party line", "soundbite", "quid pro quo",
        "inside the Beltway", "super PAC", "swing voter", "red tape", "cloture", "whip count",
        "floor vote", "override the veto", "executive order", "gridlock", "partisan",
        "demagogue", "populist", "the establishment", "drain the swamp", "polling numbers",
        "approval rating", "ground game", "get out the vote", "backroom deal", "horse-trading",
        "lame-duck session", "the midterms", "primary challenge", "coattails", "bully pulpit",
        "third rail", "wedge issue", "litmus test", "flip the seat", "safe seat", "battleground",
        "electoral map", "concession speech", "the recount", "lobbyist", "dark money",
        "astroturfing", "spin doctor", "message discipline", "talking head", "across the aisle",
        "the optics of it", "kingmaker",
    ],
    "medical": [
        "presents with", "differential diagnosis", "vitals", "STAT", "contraindicated",
        "acute onset", "chronic", "prognosis", "comorbidity", "triage", "code blue", "NPO",
        "elevated BP", "prescribe", "dosage", "biopsy", "malignant", "benign", "sutures",
        "IV drip", "intubate", "sepsis", "inflammation", "presenting symptom", "referral",
        "discharge", "bedside manner", "the chart", "lab results", "contagious",
        "immune response", "relapse", "in remission", "palliative", "post-op", "pre-op",
        "anesthesia", "the ICU", "the ER", "attending physician", "the resident", "rounds",
        "defibrillator", "CPR", "vital signs", "heart rate", "blood pressure",
        "oxygen saturation", "MRI", "CT scan", "X-ray", "ultrasound", "blood panel",
        "white blood cell count", "antibiotics", "antiviral", "dosage titration", "side effects",
        "adverse reaction", "allergic reaction", "quarantine", "incubation period",
        "symptomatic", "asymptomatic", "guarded condition", "stable condition",
        "critical condition", "do no harm", "the Hippocratic oath", "suture the wound",
        "fracture", "dislocation", "concussion", "hemorrhage", "transfusion", "flare-up",
        "the prognosis is poor", "vitals are crashing",
    ],
    "gaming": [
        "GG", "the meta", "nerf", "buff", "respawn", "DPS", "drawing aggro", "lag", "hitbox",
        "pay-to-win", "speedrun", "glitch", "exploit", "grinding", "loot drop", "boss fight",
        "skipped the tutorial", "rage quit", "noob", "camping", "cooldown", "hit points",
        "level up", "checkpoint", "kill streak", "overpowered", "patch notes", "hotfix",
        "matchmaking", "high ping", "frame rate", "easter egg", "side quest", "NPC",
        "microtransaction", "respec", "mana", "XP", "skill tree", "loot box", "season pass",
        "battle pass", "ranked match", "casual lobby", "smurf account", "hardcore mode",
        "permadeath", "save scumming", "quicksave", "spawn camping", "headshot",
        "friendly fire", "team kill", "ganking", "kiting", "tank and spank", "the healer",
        "DPS check", "enrage timer", "a wipe", "the raid", "the dungeon", "farming",
        "crafting", "inventory full", "the hotbar", "combo", "button mash", "frame-perfect",
        "input lag", "server tick", "desync", "hit registration", "aimbot", "wallhack",
        "the nerf hammer", "power creep", "balance patch", "the endgame", "grind to unlock",
    ],
    "sports": [
        "full-court press", "hail mary", "own goal", "red card", "yellow card",
        "sent to the bench", "overtime", "slam dunk", "foul play", "offside", "time-out",
        "MVP", "underdog", "home stretch", "photo finish", "dropped the ball",
        "moved the goalposts", "par for the course", "threw in the towel", "hat trick",
        "sudden death", "penalty kick", "halftime", "the playbook", "coach's challenge",
        "VAR review", "free agent", "on the ropes", "knockout", "doping", "sidelined",
        "the comeback", "clutch play", "draft pick", "bench warmer", "hard foul", "fast break",
        "zone defense", "man-to-man", "the pocket", "audible", "two-minute warning",
        "buzzer beater", "home-field advantage", "the playoffs", "the finals", "championship",
        "relegation", "transfer window", "scouting report", "game plan", "halftime adjustment",
        "garbage time", "blowout", "nail-biter", "extra innings", "pinch hitter", "free throw",
        "three-pointer", "turnover", "interception", "fumble", "the end zone", "touchdown",
        "field goal", "the penalty box", "power play", "face-off", "clean sheet",
        "stoppage time", "injury time", "sin bin", "the final whistle", "offside trap",
    ],
    "scifi": [
        "warp core", "hull breach", "set phasers", "airlock", "FTL jump", "hyperdrive",
        "escape pod", "life support", "oxygen levels", "cryosleep", "terraform", "wormhole",
        "tractor beam", "photon burst", "plasma conduit", "deflector shield", "stardate",
        "away team", "transporter", "dilithium", "event horizon", "gravity well",
        "docking clamp", "reactor core", "navigation array", "cargo bay", "solar flare",
        "ion storm", "command bridge", "self-destruct sequence", "jettison the cargo",
        "decompression", "beam up", "subspace signal", "warp speed", "sublight engines",
        "antimatter", "containment field", "shield harmonics", "cloaking device",
        "photon torpedo", "phaser array", "red alert", "yellow alert", "the viewscreen",
        "the holodeck", "replicator", "impulse power", "inertial dampeners", "artificial gravity",
        "oxygen scrubbers", "stasis pod", "suspended animation", "atmospheric processor",
        "hull integrity", "structural integrity field", "quantum singularity", "warp field",
        "subspace anomaly", "temporal rift", "first contact", "the prime directive",
        "escape velocity", "orbital decay", "reentry burn", "heat shield", "docking sequence",
        "mag-lock", "pressure seal", "vacuum exposure", "zero-g", "spacewalk", "an EVA",
        "mission control", "the mothership",
    ],
}

